import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8')
const exists = (p) => fs.existsSync(path.join(root, p))
const checks = []
const check = (name, ok, detail='') => checks.push({ name, ok: Boolean(ok), detail })

const edge = read('supabase/functions/exam-access/index.ts')
const mig = read('supabase/migrations/0021_strict_audit_fixes.sql')
const bootstrap = read('supabase/sql/bootstrap_all.sql')
const editor = read('src/components/QuestionEditorModal.jsx')
const qservice = read('src/services/questionBankManagement.js')
const examEditor = read('src/pages/TeacherExamEditorPage.jsx')
const finished = read('src/pages/ExamFinishedPage.jsx')
const home = read('src/pages/HomePage.jsx')
const layout = read('src/layouts/PublicLayout.jsx')
const settings = read('src/pages/TeacherSettingsPage.jsx')
const offline = read('src/utils/offlineExamQueue.js')
const studentExam = read('src/pages/StudentExamPage.jsx')

check('Migration 0021 exists', exists('supabase/migrations/0021_strict_audit_fixes.sql'))
check('Atomic answer RPC exists', /save_attempt_answer_if_newer/.test(mig))
check('Edge uses atomic answer RPC', /rpc\(['\"]save_attempt_answer_if_newer['\"]/.test(edge))
check('No direct respuestas upsert remains', !/from\(['\"]respuestas['\"]\)[\s\S]{0,120}\.upsert\(/.test(edge))
check('Student code normalized in DB', /set student_code = upper\(btrim\(student_code\)\)/.test(mig))
check('Stable student-code unique index exists', /estudiantes_student_code_ci_unique/.test(mig))
check('Future student codes are normalized by trigger', /trg_normalize_student_code/.test(mig) && /new\.student_code := upper\(btrim\(new\.student_code\)\)/.test(mig))
check('Open-student lookup uses exact code', /\.eq\(['\"]student_code['\"], internalCode\)/.test(edge) && !/\.ilike\(['\"]student_code['\"], internalCode\)/.test(edge))
check('Enrollment uses exact surnames and names in name-only mode', /firstMatches/.test(edge) && /lastMatches/.test(edge) && /return Boolean\(firstMatches && lastMatches\)/.test(edge))
check('Answer text bounded server-side', /MAX_LONG_TEXT_CHARS/.test(edge) && /respuestas_answer_text_length/.test(mig))
check('Answer payload bounded', /MAX_ANSWER_PAYLOAD_BYTES/.test(edge) && /payloadByteLength/.test(edge))
check('Nested upload questions blocked in DB', /Las subpreguntas de un caso no pueden requerir carga de archivos/.test(mig))
check('Nested upload questions blocked in editor', /CHILD_TYPES = QUESTION_TYPES\.filter\(\(type\) => !\['case_group', 'calculation_evidence', 'attachment'\]\.includes\(type\)\)/.test(editor))
check('Nested upload questions blocked in service', /subpreguntas de un caso no pueden requerir archivos/i.test(qservice))
check('Correct-answer result details implemented', /safeStudentResultDetails/.test(edge) && /correctAnswer/.test(finished))
check('Closed exams support secure result re-entry', /action === 'validate_results'/.test(edge) && /action === 'result_access'/.test(edge) && /accessCompletedResults/.test(edge))
check('Answer embargo until exam closes', /answersEmbargoed/.test(edge) && /answersEmbargoed/.test(finished))
check('Teacher feedback visibility is accurately labeled', /Respuestas \+ retroalimentación docente/.test(examEditor))
check('Hard timeout is enforced in DB', /config_auto_submit_timeout_required/.test(mig))
check('Hard timeout is no longer a misleading toggle', !/type=["']checkbox["'][^>]*checked=\{form\.autoSubmitOnTimeout\}/.test(examEditor))
check('Client revision has monotonic floor', /seedClientRevisionFloor/.test(offline) && /revisionFloor = Math\.max\(revisionFloor \+ 1, clockCandidate\)/.test(offline))
check('Student engine seeds revision floor', /seedClientRevisionFloor\(question\.answer\?\.clientRevision\)/.test(studentExam))
check('No stale demo claim on home', !/datos demostrativos|demostraci[oó]n/i.test(home))
check('No stale demo footer', !/datos de demostraci[oó]n/i.test(layout))
check('Global settings are persisted', /useGlobalSettings/.test(settings) && /Guardar configuración/.test(settings) && /evidenceAllowedMimeTypes/.test(settings))
check('Bootstrap includes migration 0021', /0021_strict_audit_fixes\.sql/.test(bootstrap))

const failed = checks.filter(c => !c.ok)
for (const c of checks) console.log(`${c.ok ? 'PASS' : 'FAIL'} - ${c.name}${c.detail ? `: ${c.detail}` : ''}`)
console.log(`\nStrict audit: ${checks.length - failed.length}/${checks.length} PASS`)
if (failed.length) process.exit(1)
